// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crudMasterApi.Entities;

namespace crudMasterApi.Migrations
{
    [DbContext(typeof(AccountingContext))]
    partial class AccountingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("crudMasterApi.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kovin",
                            PostalCode = "26220"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beograd",
                            PostalCode = "11000"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pančevo",
                            PostalCode = "26000"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Novi Sad",
                            PostalCode = "21000"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Beograd",
                            PostalCode = "11000"
                        });
                });

            modelBuilder.Entity("crudMasterApi.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Principal")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("crudMasterApi.Entities.ModuleSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdModule")
                        .HasColumnType("int");

                    b.Property<int>("IdSubject")
                        .HasColumnType("int")
                        .HasMaxLength(200);

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ModuleSubjects");
                });

            modelBuilder.Entity("crudMasterApi.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Mail = "gimeko@yahoo.com",
                            Name = "Gimnazija i ekonomska škola Branko Radičević"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Mail = "gimeko@yahoo.com",
                            Name = "Gimnazija i ekonomska škola Branko Radičević"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Mail = "gimeko@yahoo.com",
                            Name = "Gimnazija i ekonomska škola Branko Radičević"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            Mail = "gimeko@yahoo.com",
                            Name = "Gimnazija i ekonomska škola Branko Radičević"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Name = "Srednja stručna škola Mihajlo Pupin"
                        });
                });

            modelBuilder.Entity("crudMasterApi.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("crudMasterApi.Entities.Module", b =>
                {
                    b.HasOne("crudMasterApi.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("crudMasterApi.Entities.ModuleSubject", b =>
                {
                    b.HasOne("crudMasterApi.Entities.Module", "Module")
                        .WithMany("SubjectsOfModule")
                        .HasForeignKey("ModuleId");

                    b.HasOne("crudMasterApi.Entities.Subject", "Subject")
                        .WithMany("ModulesOfSubject")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("crudMasterApi.Entities.School", b =>
                {
                    b.HasOne("crudMasterApi.Entities.City", "City")
                        .WithMany("Schools")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
